#!/usr/bin/env python3

Import('env_modules')
Import('env')

env_conf = env_modules.Clone();

thirdparty_dir = '#thirdparty/cpptoml/include'

env_conf.Prepend(CPPPATH=[thirdparty_dir])

env_conf.add_source_files(env.modules_sources, "*.cpp")