#!/usr/bin/env python3

Import('env_modules')
Import('env')

env_args = env_modules.Clone();

thirdparty_dir = '#thirdparty/cxxopts/include'

env_args.Prepend(CPPPATH=[thirdparty_dir])

env_args.add_source_files(env.modules_sources, "*.cpp")
