#!/usr/bin/env python3

Import('env')

hdr_list = ['ProcessStream.h', 'ControlInterface.h','Config.h','Devoured.h']
src_list = ['main.cpp', 'ProcessStream.cpp', 'ControlInterface.cpp','Config.cpp', 'Devoured.cpp']

obj_list = env.Object(src_list)

Return('obj_list','src_list','hdr_list')