#!/usr/bin/env python3

Import('env')

env.objects = []
env.sources = []
env.headers = []

# hdr_list = ['process_stream.h', 'network.h','devoured.h','signal_handler.h']
# src_list = ['process_stream.cpp', 'network.cpp', 'devoured.cpp', 'signal_handler.cpp','protocol.cpp']

SConscript('network/SConscript')
SConscript('devoured/SConscript')

env.add_source_files(env.objects, env.sources)

#lib = env.add_library("core", env.core_sources)
#env.Prepend(LIBS=[lib])
